AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**'
    - 'spec/requests/**/*'
Metrics/BlockLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Layout/LineLength:
 Max: 150
