---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/surveys":
    get:
      summary: list surveys
      responses:
        '200':
          description: successful
    post:
      summary: create survey
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/surveys/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show survey
      responses:
        '200':
          description: successful
    patch:
      summary: update survey
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    put:
      summary: update survey
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete survey
      responses:
        '200':
          description: successful
servers:
- url: http://{host}
  variables:
    host:
      default: localhost:3000
