name: Continuous Integration
on: [push]
jobs:
  rubocop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.1'
      - run: bundle install
      - name: Rubocop
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
  test:
    runs-on: ubuntu-22.04
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.1'
    - name: Build and run test
      env:
        DATABASE_URL: db://db:@localhost:5432/pisano_api_test
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler:1.17.3
        bundle install --jobs 4 --retry 3
        bundle exec rails db:create
        bundle exec rails db:migrate
        RAILS_ENV=test bundle exec rspec
